CREATE TYPE "public"."status" AS ENUM('completed', 'inProgress');--> statement-breakpoint
CREATE TABLE "mitarbeiter" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mitarbeiter_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firstName" varchar(255) NOT NULL,
	"lastName" varchar(255) NOT NULL,
	"kuerzel" varchar(255) NOT NULL,
	"skill_name" varchar(255),
	"skill_level" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"market" varchar(100),
	"name" varchar(255) NOT NULL,
	"description" text,
	"start" date,
	"end" date,
	"status" "status",
	"priority" integer,
	"project_manager" varchar(255),
	"progress" integer,
	"customer" varchar(255),
	"comment" text
);
--> statement-breakpoint
CREATE TABLE "skills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100),
	"level" integer
);
