CREATE TYPE "public"."status" AS ENUM('completed', 'inProgress', '');--> statement-breakpoint
CREATE TABLE "employee" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employee_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"firstName" varchar(255) NOT NULL,
	"lastName" varchar(255) NOT NULL,
	"kuerzel" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "employeeToSkill" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "employeeToSkill_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"employee_id" integer,
	"skill_id" integer,
	"skill_level" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "projects_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"market" varchar(100),
	"name" varchar(255) NOT NULL,
	"description" text,
	"start" date,
	"end" date,
	"status" "status",
	"priority" integer,
	"project_manager" varchar(255),
	"progress" integer,
	"customer" varchar(255),
	"comment" text
);
--> statement-breakpoint
CREATE TABLE "skills" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100),
	"level" integer
);
--> statement-breakpoint
ALTER TABLE "employeeToSkill" ADD CONSTRAINT "employeeToSkill_employee_id_employee_id_fk" FOREIGN KEY ("employee_id") REFERENCES "public"."employee"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "employeeToSkill" ADD CONSTRAINT "employeeToSkill_skill_id_skills_id_fk" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON DELETE no action ON UPDATE no action;